version: "3.9"

services:

  ubuntu:
    image: nginx_from_scratch_nginx
    container_name: nginx_from_scratch2
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - "80:80"
      # - "8080:8080"
      # - "5000:5000"

